command /togglecursor:
    permission: op 
    trigger:
        if {cursor_mode::%player%} = false:
            cursor(player)
        else:
            set {cursor_mode::%player%} to false


function cursor(p: player):

    set {_p}'s gamemode to spectator
    spawn_cursor({_p})
    set {_d} to last spawned text display

    set {cursor_mode::%{_p}%} to true
    set {_loc} to {_p}'s location 

    while {cursor_mode::%{_p}%} is true:
        set {_v} to vector in direction of {_p} * 5
        set {_loc}'s yaw to {_p}'s yaw
        set {_loc}'s pitch to {_p}'s pitch
        if distance between {_p}'s location and {_loc} != 0:
            teleport {_p} to {_loc}
        teleport {_d} to {_p} ~ {_v}
        wait 2 ticks



function spawn_cursor(p: player):
    spawn a text display at {_p}:
        set {_d} to entity
        set display text of {_d} to "&f&l+" # Change later
        set display teleportation duration of {_d} to 2
        set display scale of {_d} to vector(2.5,2.5,2.5)
        set billboard of {_d} to center